# Note: With the introduction of workspaces we recommend using workspaces with APIOps when possible to limit what can be extracted whenever possible. 
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview

# apiNames not specified = extract ALL APIs

diagnosticNames:
  - azuremonitor

loggerNames:
  - azuremonitor

# Resources excluded from extraction (empty array = extract none)
namedValueNames: []
productNames: []
subscriptionNames: []
backendNames: []
tagNames: []
policyFragmentNames: []
