openapi: 3.0.1
info:
  title: Basic Calculator
  description: Arithmetic operations over HTTP!
  version: '1.0'
servers:
  - url: https://workshop-apim.azure-api.net/calc
paths:
  /sumar/:
    get:
      summary: Add two integers
      description: Responds with the sum of two numbers.
      operationId: Add-two-integers
      parameters:
        - name: num1
          in: query
          description: First operand. Default value is <code>51</code>.
          required: true
          schema:
            type: integer
            default: 51
        - name: num2
          in: query
          description: Second operand. Default value is <code>49</code>.
          required: true
          schema:
            type: integer
            default: 49
      responses:
        '200':
          description: Successful operation
          content:
            application/json: { }
  /restar/:
    get:
      summary: Subtract two integers
      description: Responds with the difference between two numbers.
      operationId: Subtract-two-integers
      parameters:
        - name: num1
          in: query
          description: First operand. Default value is <code>100</code>.
          required: true
          schema:
            type: integer
            default: 100
        - name: num2
          in: query
          description: Second operand. Default value is <code>50</code>.
          required: true
          schema:
            type: integer
            default: 50
      responses:
        '200':
          description: Successful operation
          content:
            application/json: { }
  /dividir/:
    get:
      summary: Divide two integers
      description: Responds with the quotient of two numbers.
      operationId: Divide-two-integers
      parameters:
        - name: num1
          in: query
          description: First operand. Default value is <code>100</code>.
          required: true
          schema:
            type: integer
            default: 100
        - name: num2
          in: query
          description: Second operand. Default value is <code>20</code>.
          required: true
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Successful operation
          content:
            application/json: { }
  /multiplicar/:
    get:
      summary: Multiply two integers
      description: Responds with the product of two numbers.
      operationId: Multiply-two-integers
      parameters:
        - name: num1
          in: query
          description: First operand. Default value is <code>20</code>.
          required: true
          schema:
            type: integer
            default: 20
        - name: num2
          in: query
          description: Second operand. Default value is <code>5</code>.
          required: true
          schema:
            type: integer
            default: 5
      responses:
        '200':
          description: Successful operation
          content:
            application/json: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]